spring:
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: continuedevelop@gmail.com
    password: cucupfpmknijxkhm
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/entertain?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    check-templates-location: true
    suffix: .html
    mode: HTML5
    cache: false
    order: 0
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 849784182633-0281623723ls8vuv5pcrauj3u0v2ivcf.apps.googleusercontent.com
            client-secret: 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
#  profiles:
#    include: google
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

app:
  host: http://localhost:8080
  title: Entertainment Among Us
  version: ver.0.1
  help-email: continuedevelop@gmail.com

#  token-available-period: 60
#  host:
#    api: http://localhost:8080
#    front: https://banking-api.sample.com
